<?php

return [
    'context_groups' => [
        'policies' => [
            'label' => 'Policies',
            'icon' => 'fas fa-gavel',
            'order' => 10000,
            'route' => NULL,
            'url' => 'hr/dashboard-policies-overview',
        ],
        'reports' => [
            'label' => 'Reports',
            'icon' => 'fas fa-file-alt',
            'order' => 10000,
            'route' => NULL,
            'url' => 'reports',
        ],
        'people' => [
            'label' => 'People',
            'icon' => 'fas fa-user-friends',
            'order' => 999,
            'route' => NULL,
            'url' => 'hr/dashboard-people-overview',
        ],
        'payroll' => [
            'label' => 'Payroll',
            'icon' => 'fas fa-user-tie',
            'order' => 999,
            'route' => NULL,
            'url' => 'hr/dashboard-payroll-overview',
        ],
        'leave' => [
            'label' => 'Leave',
            'icon' => 'fas fa-user-check',
            'order' => 1000,
            'route' => NULL,
            'url' => 'hr/dashboard-leave-overview',
        ],
        'time' => [
            'label' => 'Time',
            'icon' => 'fas fa-user-clock',
            'order' => 999,
            'route' => NULL,
            'url' => 'hr/dashboard-time-overview',
        ],
    ],
    'contexts' => [
        'policies' => [
            [
                'key' => 'attendance_policy',
                'label' => 'Attendance Policies',
                'icon' => 'fas fa-gavel',
                'route' => '/hr/attendance-policies',
                'permission' => 'view_attendance_policy',
                'order' => 999,
                'page_title' => NULL,
            ],
            [
                'key' => 'overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/hr/dashboard-policies-overview',
                'permission' => 'view_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'policy_assignment',
                'label' => 'Policy Assignments',
                'icon' => 'fas fa-gavel',
                'route' => '/hr/policy-assignments',
                'permission' => 'view_policy_assignment',
                'order' => 999,
                'page_title' => NULL,
            ],
            [
                'key' => 'work_pattern',
                'label' => 'Work Patterns',
                'icon' => 'fas fa-calendar-week',
                'route' => '/hr/work-patterns',
                'permission' => 'view_work_pattern',
                'order' => 999,
                'page_title' => NULL,
            ],
            [
                'key' => 'employee_work_pattern',
                'label' => 'Employee Work Pattern',
                'icon' => 'fas fa-calendar-week',
                'route' => '/hr/employee-work-patterns',
                'permission' => 'view_employee_work_pattern',
                'order' => 999,
                'page_title' => NULL,
            ],
        ],
        'time' => [
            [
                'key' => 'shift',
                'label' => 'Shifts',
                'icon' => 'fas fa-calendar-day',
                'route' => '/hr/shifts',
                'permission' => 'view_shift',
                'order' => 999,
                'page_title' => NULL,
            ],
            [
                'key' => 'overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/hr/dashboard-time-overview',
                'permission' => 'view_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'saved_report',
                'label' => 'Reports',
                'icon' => 'fas fa-file-alt me-2',
                'route' => '/reports',
                'permission' => 'view_saved_report',
                'order' => 10000000,
                'page_title' => NULL,
            ],
            [
                'key' => 'attendance',
                'label' => 'Attendance',
                'icon' => 'fas fa-user-clock',
                'route' => '/hr/attendances',
                'permission' => 'view_attendance',
                'order' => 1,
                'page_title' => 'Attendance',
            ],
            [
                'key' => 'shift_schedule',
                'label' => 'Shift Schedules',
                'icon' => 'fas fa-calendar-alt',
                'route' => '/hr/shift-schedules',
                'permission' => 'view_shift_schedule',
                'order' => 999,
                'page_title' => NULL,
            ],
            [
                'key' => 'holiday_calendar',
                'label' => 'Holiday Calendars',
                'icon' => 'fas fa-calendar-alt',
                'route' => '/hr/holiday-calendars',
                'permission' => 'view_holiday_calendar',
                'order' => 999,
                'page_title' => NULL,
            ],
            [
                'key' => 'holiday',
                'label' => 'Holidays',
                'icon' => 'fas fa-gift',
                'route' => '/hr/holidays',
                'permission' => 'view_holiday',
                'order' => 999,
                'page_title' => NULL,
            ],
        ],
        'reports' => [
            [
                'key' => 'saved_report',
                'label' => 'Saved Reports',
                'icon' => 'fas fa-user',
                'route' => '/saved-reports',
                'permission' => 'view_saved_report',
                'order' => 999,
                'page_title' => NULL,
            ],
        ],
        'people' => [
            [
                'key' => 'overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/hr/dashboard-people-overview',
                'permission' => 'view_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'employee',
                'label' => 'Employees',
                'icon' => 'fas fa-user-friends',
                'route' => '/hr/employees',
                'permission' => 'view_employee',
                'order' => 999,
                'page_title' => NULL,
            ],
            [
                'key' => 'employee_position',
                'label' => 'Job Information',
                'icon' => 'fas fa-briefcase',
                'route' => '/hr/employee-positions',
                'permission' => 'view_employee_position',
                'order' => 999,
                'page_title' => NULL,
            ],
            [
                'key' => 'employee_profile',
                'label' => 'Profiles',
                'icon' => 'fas fa-user-circle',
                'route' => '/hr/employee-profiles',
                'permission' => 'view_employee_profile',
                'order' => 999,
                'page_title' => NULL,
            ],
            [
                'key' => 'document',
                'label' => 'Documents',
                'icon' => 'fas fa-file',
                'route' => '/hr/documents',
                'permission' => 'view_document',
                'order' => 999,
                'page_title' => NULL,
            ],
        ],
        'payroll' => [
            [
                'key' => 'overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/hr/dashboard-payroll-overview',
                'permission' => 'view_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'pay_schedule',
                'label' => 'Pay Schedules',
                'icon' => 'fas fa-calendar-alt',
                'route' => '/hr/pay-schedules',
                'permission' => 'view_pay_schedule',
                'order' => 999,
                'page_title' => NULL,
            ],
            [
                'key' => 'employee_payroll_profile',
                'label' => 'Payroll Employees',
                'icon' => 'fas fa-user-tie',
                'route' => '/hr/employee-payroll-profiles',
                'permission' => 'view_employee_payroll_profile',
                'order' => 2,
                'page_title' => NULL,
            ],
            [
                'key' => 'payroll_run',
                'label' => 'Pay Runs',
                'icon' => 'fas fa-file-invoice-dollar',
                'route' => '/hr/payroll-runs',
                'permission' => 'view_payroll_run',
                'order' => 999,
                'page_title' => NULL,
            ],
            [
                'key' => 'payroll_payslip',
                'label' => 'Payslips',
                'icon' => 'fas fa-receipt',
                'route' => '/hr/payroll-payslips',
                'permission' => 'view_payroll_payslip',
                'order' => 999,
                'page_title' => NULL,
            ],
        ],
        'leave' => [
            [
                'key' => 'overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/hr/dashboard-leave-overview',
                'permission' => 'view_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'leave_type',
                'label' => 'Leave Types',
                'icon' => 'fas fa-tags',
                'route' => '/hr/leave-types',
                'permission' => 'view_leave_type',
                'order' => 999,
                'page_title' => NULL,
            ],
            [
                'key' => 'leave_request',
                'label' => 'Leave Requests',
                'icon' => 'fas fa-calendar-alt',
                'route' => '/hr/leave-requests',
                'permission' => 'view_leave_request',
                'order' => 1,
                'page_title' => NULL,
            ],
        ],
        'leave_balance' => [
            [
                'key' => 'leave_balance',
                'label' => 'Leave Balances',
                'icon' => 'fas fa-scale-balanced',
                'route' => '/leave-balances',
                'permission' => 'view_leave_balance',
                'order' => 999,
                'page_title' => NULL,
            ],
        ],
        'leave_approver' => [
            [
                'key' => 'leave_approver',
                'label' => 'Leave Approvers',
                'icon' => 'fas fa-user-shield',
                'route' => '/leave-approvers',
                'permission' => 'view_leave_approver',
                'order' => 999,
                'page_title' => NULL,
            ],
        ],
        'attendance_adjustment' => [
            [
                'key' => 'attendance_adjustment',
                'label' => 'Attendance Adjustments',
                'icon' => 'fas fa-edit',
                'route' => '/attendance-adjustments',
                'permission' => 'view_attendance_adjustment',
                'order' => 999,
                'page_title' => NULL,
            ],
        ],
        'clock_event' => [
            [
                'key' => 'clock_event',
                'label' => 'Clock Events',
                'icon' => 'fas fa-clock',
                'route' => '/clock-events',
                'permission' => 'view_clock_event',
                'order' => 999,
                'page_title' => NULL,
            ],
        ],
        'attendance_session' => [
            [
                'key' => 'attendance_session',
                'label' => 'Attendance Sessions',
                'icon' => 'fas fa-hourglass-half',
                'route' => '/attendance-sessions',
                'permission' => 'view_attendance_session',
                'order' => 999,
                'page_title' => NULL,
            ],
        ],
    ],
    'layout' => [
        'top_bar' => [
            'enabled' => true,
        ],
        'context_menu' => [
            'type' => 'sidebar',
            'position' => 'left',
            'allow_switch' => true,
            'default_type' => 'sidebar',
        ],
        'sidebar' => [
            'initial_state' => 'full',
        ],
        'bottom_bar' => [
            'enabled' => true,
        ],
        'breadcrumb' => [
            'enabled' => true,
        ],
        'title' => [
            'enabled' => true,
        ],
    ],
    'shared_items' => [
        'header' => [],
        'footer' => [],
    ],
    'shared_top_items' => [
        'left' => [],
        'right' => [],
    ],
];
