<?php

return [
    [
    'title' => 'Attendance Policies',
    'icon' => 'fas fa-file-contract',
    'url' => 'hr/attendance-policies',
    'permission' => 'view_attendance_policy',
    'key' => 'attendance_policy',
],
    [
    'title' => 'Saved Reports',
    'icon' => 'fas fa-cube',
    'url' => 'hr/saved-reports',
    'permission' => 'view_saved_report',
    'key' => 'saved_report',
],
    [
    'title' => 'Overviews',
    'icon' => 'fas fa-cube',
    'url' => 'hr/overviews',
    'permission' => 'view_overview',
    'key' => 'overview',
],
    [
    'title' => 'Employee Groups',
    'icon' => 'fas fa-layer-group',
    'url' => 'hr/employee-groups',
    'permission' => 'view_employee_group',
    'key' => 'employee_group',
],
    [
    'title' => 'Tags',
    'icon' => 'fas fa-tag',
    'url' => 'hr/tags',
    'permission' => 'view_tag',
    'key' => 'tag',
],
    [
    'title' => 'Employees',
    'icon' => 'fas fa-user-tie',
    'url' => 'hr/employees',
    'permission' => 'view_employee',
    'key' => 'employee',
],
    [
    'title' => 'Employee Job Histories',
    'icon' => 'fas fa-timeline',
    'url' => 'hr/employee-job-histories',
    'permission' => 'view_employee_job_history',
    'key' => 'employee_job_history',
],
    [
    'title' => 'Employee Profiles',
    'icon' => 'fas fa-user-tie',
    'url' => 'hr/employee-profiles',
    'permission' => 'view_employee_profile',
    'key' => 'employee_profile',
],
    [
    'title' => 'Teams',
    'icon' => 'fas fa-users',
    'url' => 'hr/teams',
    'permission' => 'view_team',
    'key' => 'team',
],
    [
    'title' => 'Documents',
    'icon' => 'fas fa-file-alt',
    'url' => 'hr/documents',
    'permission' => 'view_document',
    'key' => 'document',
],
    [
    'title' => 'Policy Assignments',
    'icon' => 'fas fa-tasks',
    'url' => 'hr/policy-assignments',
    'permission' => 'view_policy_assignment',
    'key' => 'policy_assignment',
],
    [
    'title' => 'Work Patterns',
    'icon' => 'fas fa-calendar-alt',
    'url' => 'hr/work-patterns',
    'permission' => 'view_work_pattern',
    'key' => 'work_pattern',
],
    [
    'title' => 'Employee Work Patterns',
    'icon' => 'fas fa-user-tag',
    'url' => 'hr/employee-work-patterns',
    'permission' => 'view_employee_work_pattern',
    'key' => 'employee_work_pattern',
],
    [
    'title' => 'Pay Schedules',
    'icon' => 'fas fa-calendar-week',
    'url' => 'hr/pay-schedules',
    'permission' => 'view_pay_schedule',
    'key' => 'pay_schedule',
],
    [
    'title' => 'Employee Payroll Profiles',
    'icon' => 'fas fa-id-card',
    'url' => 'hr/employee-payroll-profiles',
    'permission' => 'view_employee_payroll_profile',
    'key' => 'employee_payroll_profile',
],
    [
    'title' => 'Payroll Runs',
    'icon' => 'fas fa-chart-line',
    'url' => 'hr/payroll-runs',
    'permission' => 'view_payroll_run',
    'key' => 'payroll_run',
],
    [
    'title' => 'Payroll Payslips',
    'icon' => 'fas fa-file-invoice',
    'url' => 'hr/payroll-payslips',
    'permission' => 'view_payroll_payslip',
    'key' => 'payroll_payslip',
],
    [
    'title' => 'Payroll Policies',
    'icon' => 'fas fa-file-contract',
    'url' => 'hr/payroll-policies',
    'permission' => 'view_payroll_policy',
    'key' => 'payroll_policy',
],
    [
    'title' => 'Payroll Run Adjustments',
    'icon' => 'fas fa-pen-alt',
    'url' => 'hr/payroll-run-adjustments',
    'permission' => 'view_payroll_run_adjustment',
    'key' => 'payroll_run_adjustment',
],
    [
    'title' => 'Employee Adjustment Profiles',
    'icon' => 'fas fa-user-edit',
    'url' => 'hr/employee-adjustment-profiles',
    'permission' => 'view_employee_adjustment_profile',
    'key' => 'employee_adjustment_profile',
],
    [
    'title' => 'Payslip Items',
    'icon' => 'fas fa-receipt',
    'url' => 'hr/payslip-items',
    'permission' => 'view_payslip_item',
    'key' => 'payslip_item',
],
    [
    'title' => 'Payroll Policy Assignments',
    'icon' => 'fas fa-tasks',
    'url' => 'hr/payroll-policy-assignments',
    'permission' => 'view_payroll_policy_assignment',
    'key' => 'payroll_policy_assignment',
],
    [
    'title' => 'Employee Positions',
    'icon' => 'fas fa-suitcase',
    'url' => 'hr/employee-positions',
    'permission' => 'view_employee_position',
    'key' => 'employee_position',
],
    [
    'title' => 'Leave Types',
    'icon' => 'fas fa-tag',
    'url' => 'hr/leave-types',
    'permission' => 'view_leave_type',
    'key' => 'leave_type',
],
    [
    'title' => 'Leave Requests',
    'icon' => 'fas fa-calendar-plus',
    'url' => 'hr/leave-requests',
    'permission' => 'view_leave_request',
    'key' => 'leave_request',
],
    [
    'title' => 'Leave Balances',
    'icon' => 'fas fa-scale-balanced',
    'url' => 'hr/leave-balances',
    'permission' => 'view_leave_balance',
    'key' => 'leave_balance',
],
    [
    'title' => 'Leave Approvers',
    'icon' => 'fas fa-user-shield',
    'url' => 'hr/leave-approvers',
    'permission' => 'view_leave_approver',
    'key' => 'leave_approver',
],
    [
    'title' => 'Attendances',
    'icon' => 'fas fa-user-clock',
    'url' => 'hr/attendances',
    'permission' => 'view_attendance',
    'key' => 'attendance',
],
    [
    'title' => 'Attendance Adjustments',
    'icon' => 'fas fa-edit',
    'url' => 'hr/attendance-adjustments',
    'permission' => 'view_attendance_adjustment',
    'key' => 'attendance_adjustment',
],
    [
    'title' => 'Shift Schedules',
    'icon' => 'fas fa-calendar-check',
    'url' => 'hr/shift-schedules',
    'permission' => 'view_shift_schedule',
    'key' => 'shift_schedule',
],
    [
    'title' => 'Clock Events',
    'icon' => 'fas fa-clock',
    'url' => 'hr/clock-events',
    'permission' => 'view_clock_event',
    'key' => 'clock_event',
],
    [
    'title' => 'Attendance Sessions',
    'icon' => 'fas fa-hourglass-half',
    'url' => 'hr/attendance-sessions',
    'permission' => 'view_attendance_session',
    'key' => 'attendance_session',
],
    [
    'title' => 'Holiday Calendars',
    'icon' => 'fas fa-calendar-days',
    'url' => 'hr/holiday-calendars',
    'permission' => 'view_holiday_calendar',
    'key' => 'holiday_calendar',
],
    [
    'title' => 'Holidays',
    'icon' => 'fas fa-gift',
    'url' => 'hr/holidays',
    'permission' => 'view_holiday',
    'key' => 'holiday',
],
];
