<?php

return [
    [
    'itemType' => 'item-separator',
    'title' => '<h6 class="ps-3 mt-4 mb-2 text-uppercase text-xs font-weight-bolder opacity-6 group-title">Policies</h6>',
    'url' => null,
],
    [
    'title' => 'Attendance Policies',
    'icon' => 'fas fa-gavel',
    'url' => 'hr/hr/attendance-policies',
    'permission' => 'view_attendance_policy',
    'groupTitle' => 'Policies',
],
    [
    'title' => 'Saved Reports',
    'icon' => 'fas fa-cube',
    'url' => 'hr/saved-reports',
    'permission' => 'view_saved_report',
],
    [
    'title' => 'Overview',
    'icon' => 'fas fa-chart-bar',
    'url' => 'hr/hr/dashboard-people-overview',
    'permission' => 'view_overview',
    'order' => 1,
],
    [
    'title' => 'Employees',
    'icon' => 'fas fa-user-friends',
    'url' => 'hr/hr/employees',
    'permission' => 'view_employee',
    'order' => 2,
],
    [
    'title' => 'Job History',
    'icon' => 'fas fa-history',
    'url' => 'hr/hr/employee-job-histories',
    'permission' => 'view_employee_job_history',
],
    [
    'title' => 'Profiles',
    'icon' => 'fas fa-user-circle',
    'url' => 'hr/hr/employee-profiles',
    'permission' => 'view_employee_profile',
    'order' => 3,
],
    [
    'title' => 'Employee Groups',
    'icon' => 'fas fa-users',
    'url' => 'hr/hr/employee-groups',
    'permission' => 'view_employee_group',
],
    [
    'itemType' => 'item-separator',
    'title' => '<h6 class="ps-3 mt-4 mb-2 text-uppercase text-xs font-weight-bolder opacity-6 group-title">People Management</h6>',
    'url' => null,
],
    [
    'title' => 'Documents',
    'icon' => 'fas fa-file',
    'url' => 'hr/hr/documents',
    'permission' => 'view_document',
    'groupTitle' => 'People Management',
],
    [
    'title' => 'Overview',
    'icon' => 'fas fa-chart-bar',
    'url' => 'hr/hr/dashboard-policies-overview',
    'permission' => 'view_overview',
    'order' => 1,
],
    [
    'title' => 'Policy Assignments',
    'icon' => 'fas fa-gavel',
    'url' => 'hr/hr/policy-assignments',
    'permission' => 'view_policy_assignment',
],
    [
    'itemType' => 'item-separator',
    'title' => '<h6 class="ps-3 mt-4 mb-2 text-uppercase text-xs font-weight-bolder opacity-6 group-title">Scheduling</h6>',
    'url' => null,
],
    [
    'title' => 'Work Patterns',
    'icon' => 'fas fa-calendar-week',
    'url' => 'hr/hr/work-patterns',
    'permission' => 'view_work_pattern',
    'groupTitle' => 'Scheduling',
],
    [
    'title' => 'Employee Work Pattern',
    'icon' => 'fas fa-calendar-week',
    'url' => 'hr/hr/employee-work-patterns',
    'permission' => 'view_employee_work_pattern',
],
    [
    'title' => 'Overview',
    'icon' => 'fas fa-chart-bar',
    'url' => 'hr/hr/dashboard-payroll-overview',
    'permission' => 'view_overview',
    'order' => 1,
],
    [
    'title' => 'Pay Schedules',
    'icon' => 'fas fa-calendar-alt',
    'url' => 'hr/hr/pay-schedules',
    'permission' => 'view_pay_schedule',
    'order' => 1,
],
    [
    'title' => 'Employee Profiles',
    'icon' => 'fas fa-user-tie',
    'url' => 'hr/hr/employee-payroll-profiles',
    'permission' => 'view_employee_payroll_profile',
    'order' => 2,
],
    [
    'title' => 'Payroll Runs',
    'icon' => 'fas fa-file-invoice-dollar',
    'url' => 'hr/hr/payroll-runs',
    'permission' => 'view_payroll_run',
    'order' => 3,
],
    [
    'title' => 'Payslips',
    'icon' => 'fas fa-receipt',
    'url' => 'hr/hr/payroll-payslips',
    'permission' => 'view_payroll_payslip',
    'order' => 3,
],
    [
    'title' => 'Policies',
    'icon' => 'fas fa-gavel',
    'url' => 'hr/hr/payroll-policies',
    'permission' => 'view_payroll_policy',
    'order' => 6,
],
    [
    'title' => 'One‑Time Adjustments',
    'icon' => 'fas fa-edit',
    'url' => 'hr/hr/payroll-run-adjustments',
    'permission' => 'view_payroll_run_adjustment',
    'order' => 5,
],
    [
    'title' => 'Recurring Adjustments',
    'icon' => 'fas fa-sync-alt',
    'url' => 'hr/hr/employee-adjustment-profiles',
    'permission' => 'view_employee_adjustment_profile',
    'order' => 4,
],
    [
    'title' => 'Payslip Items',
    'icon' => 'fas fa-list-ul',
    'url' => 'hr/hr/payslip-items',
    'permission' => 'view_payslip_item',
],
    [
    'title' => 'Policy Assignments',
    'icon' => 'fas fa-link',
    'url' => 'hr/hr/payroll-policy-assignments',
    'permission' => 'view_payroll_policy_assignment',
    'order' => 7,
],
    [
    'title' => 'Current Job',
    'icon' => 'fas fa-briefcase',
    'url' => 'hr/hr/employee-positions',
    'permission' => 'view_employee_position',
    'order' => 4,
],
    [
    'title' => 'Overview',
    'icon' => 'fas fa-chart-bar',
    'url' => 'hr/hr/dashboard-leave-overview',
    'permission' => 'view_overview',
    'order' => 1,
],
    [
    'title' => 'Leave Types',
    'icon' => 'fas fa-tags',
    'url' => 'hr/hr/leave-types',
    'permission' => 'view_leave_type',
],
    [
    'title' => 'Leave Requests',
    'icon' => 'fas fa-calendar-alt',
    'url' => 'hr/hr/leave-requests',
    'permission' => 'view_leave_request',
    'order' => 1,
],
    [
    'title' => 'Leave Balances',
    'icon' => 'fas fa-scale-balanced',
    'url' => 'hr/leave-balances',
    'permission' => 'view_leave_balance',
],
    [
    'title' => 'Leave Approvers',
    'icon' => 'fas fa-user-shield',
    'url' => 'hr/leave-approvers',
    'permission' => 'view_leave_approver',
],
    [
    'title' => 'Overview',
    'icon' => 'fas fa-chart-bar',
    'url' => 'hr/hr/dashboard-time-overview',
    'permission' => 'view_overview',
    'order' => 1,
],
    [
    'title' => 'Reports',
    'icon' => 'fas fa-file-alt me-2',
    'url' => 'hr/reports',
    'permission' => 'view_saved_report',
    'order' => 10000000,
],
    [
    'itemType' => 'item-separator',
    'title' => '<h6 class="ps-3 mt-4 mb-2 text-uppercase text-xs font-weight-bolder opacity-6 group-title">Time Tracking</h6>',
    'url' => null,
],
    [
    'title' => 'Attendance',
    'icon' => 'fas fa-user-clock',
    'url' => 'hr/hr/attendances',
    'permission' => 'view_attendance',
    'groupTitle' => 'Time Tracking',
    'order' => 1,
],
    [
    'title' => 'Attendance Adjustments',
    'icon' => 'fas fa-edit',
    'url' => 'hr/attendance-adjustments',
    'permission' => 'view_attendance_adjustment',
],
    [
    'title' => 'Shift Schedules',
    'icon' => 'fas fa-calendar-alt',
    'url' => 'hr/hr/shift-schedules',
    'permission' => 'view_shift_schedule',
    'groupTitle' => 'Scheduling',
],
    [
    'title' => 'Clock Events',
    'icon' => 'fas fa-clock',
    'url' => 'hr/clock-events',
    'permission' => 'view_clock_event',
],
    [
    'title' => 'Attendance Sessions',
    'icon' => 'fas fa-hourglass-half',
    'url' => 'hr/attendance-sessions',
    'permission' => 'view_attendance_session',
],
    [
    'title' => 'Holiday Calendars',
    'icon' => 'fas fa-calendar-alt',
    'url' => 'hr/hr/holiday-calendars',
    'permission' => 'view_holiday_calendar',
    'groupTitle' => 'Scheduling',
],
    [
    'title' => 'Holidays',
    'icon' => 'fas fa-gift',
    'url' => 'hr/hr/holidays',
    'permission' => 'view_holiday',
    'groupTitle' => 'Scheduling',
],
];
